import type { APIRoute } from "astro";
import { sql } from "../../lib/db";
import { authorizePublish, publisherIp } from "../../lib/auth";
import { generateCode, generateHash, hashCode } from "../../lib/codes";
import { parsePublishPayload } from "../../lib/publish-validate";

export const POST: APIRoute = async ({ request }) => {
  if (!(await authorizePublish(request))) {
    return json({ error: "unauthorized" }, 401);
  }

  let rawPayload: unknown;
  try {
    rawPayload = await request.json();
  } catch {
    return json({ error: "invalid_json" }, 400);
  }

  const parsed = parsePublishPayload(rawPayload);
  if (!parsed.ok) return json({ error: parsed.error }, 400);
  const { title: cleanTitle, bodyMd, code: codeSpec } = parsed.value;

  let code: string | null = null;
  let codeAutoGenerated = false;
  let codeHash: string | null = null;
  let codeSalt: string | null = null;
  if (codeSpec === "auto") {
    code = generateCode(6);
    codeAutoGenerated = true;
  } else if (typeof codeSpec === "string") {
    code = codeSpec;
  }
  if (code) {
    const hashed = await hashCode(code);
    codeHash = hashed.hash;
    codeSalt = hashed.salt;
  }

  const ip = publisherIp(request);
  const byteSize = new Blob([bodyMd]).size;

  // Race-free insert: on hash collision the unique constraint fires, we
  // get back zero rows from RETURNING, and we retry with a fresh hash.
  let hash = "";
  for (let attempt = 0; attempt < 8; attempt++) {
    const candidate = generateHash(10);
    const inserted = await sql<{ hash: string }[]>`
      insert into specs
        (hash, title, body_md, code_hash, code_salt, publisher_ip, byte_size)
      values
        (${candidate}, ${cleanTitle}, ${bodyMd}, ${codeHash}, ${codeSalt},
         ${ip}, ${byteSize})
      on conflict (hash) do nothing
      returning hash
    `;
    if (inserted.length === 1) {
      hash = inserted[0]!.hash;
      break;
    }
  }
  if (!hash) return json({ error: "hash_collision" }, 500);

  // Only echo the code when the server generated it — the caller already
  // knows the value they supplied, and echoing risks ending up in
  // proxy/log entries.
  return json({
    hash,
    url: `https://samospec.dev/s/${hash}`,
    ...(codeAutoGenerated && code ? { code } : {}),
  });
};

function json(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "content-type": "application/json" },
  });
}
