// Copyright 2026 Nikolay Samokhvalov.

/**
 * Config-aware path resolver for samospec workspace dirs.
 *
 * Two top-level locations are configurable (via `.samo/config.json`
 * `paths` section) so users can host samospec artifacts where their
 * static-site host expects them (GitHub Pages root, GitLab Pages
 * `public/`, repo `docs/`, etc.):
 *
 *   - `paths.spec_dir`        — working drafts. Default: `.samo/spec`.
 *                               Each spec slug lives at
 *                               `<spec_dir>/<slug>/{SPEC.md,TLDR.md,...}`.
 *   - `paths.blueprints_dir`  — published snapshots. Default: `blueprints`.
 *                               Each published slug lives at
 *                               `<blueprints_dir>/<slug>/SPEC.md`.
 *
 * Runtime / config files (`.samo/config.json`, `.samo/.lock`,
 * `.samo/cache/`, `.samo/transcripts/`) are NOT covered here — they
 * always live under `.samo/`.
 *
 * Defaults preserve current samospec behavior. The forthcoming dir
 * rename (`.samo/spec/` → `samospec/spec/`, `blueprints/` →
 * `samospec/blueprints/`) flips these defaults; configuration is the
 * mechanism that lets users keep the old layout if they prefer.
 */

import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import { z } from "zod";

const pathsConfigSchema = z
  .object({
    spec_dir: z.string().min(1).optional(),
    blueprints_dir: z.string().min(1).optional(),
  })
  .strict();

type PathsConfig = z.infer<typeof pathsConfigSchema>;

export interface SamoPaths {
  /** Absolute path to spec base dir (working drafts at `<specDir>/<slug>/`). */
  readonly specDir: string;
  /** Absolute path to blueprints base dir (published at `<blueprintsDir>/<slug>/`). */
  readonly blueprintsDir: string;
  /** The relative `spec_dir` actually used (resolved or default). */
  readonly specDirRel: string;
  /** The relative `blueprints_dir` actually used (resolved or default). */
  readonly blueprintsDirRel: string;
}

export const DEFAULT_SPEC_DIR_REL: string = path.join(".samo", "spec");
export const DEFAULT_BLUEPRINTS_DIR_REL = "blueprints";

/**
 * Resolve workspace paths for `cwd`, honoring `.samo/config.json`
 * `paths` overrides if present. Each call re-reads the config file —
 * cheap (<1KB JSON) and keeps the resolver stateless.
 *
 * Throws if the config file exists but is malformed (JSON or schema).
 */
export function resolvePaths(cwd: string): SamoPaths {
  const cfg = readPathsConfig(cwd);
  const specRel = cfg.spec_dir ?? DEFAULT_SPEC_DIR_REL;
  const bpRel = cfg.blueprints_dir ?? DEFAULT_BLUEPRINTS_DIR_REL;
  rejectAbsolute("spec_dir", specRel);
  rejectAbsolute("blueprints_dir", bpRel);
  rejectEscape("spec_dir", specRel);
  rejectEscape("blueprints_dir", bpRel);
  return {
    specDir: path.resolve(cwd, specRel),
    blueprintsDir: path.resolve(cwd, bpRel),
    specDirRel: specRel,
    blueprintsDirRel: bpRel,
  };
}

/** `<spec_dir>/<slug>` — working draft slug dir. */
export function specSlugDir(cwd: string, slug: string): string {
  return path.join(resolvePaths(cwd).specDir, slug);
}

/** `<blueprints_dir>/<slug>` — published slug dir. */
export function blueprintSlugDir(cwd: string, slug: string): string {
  return path.join(resolvePaths(cwd).blueprintsDir, slug);
}

/** `<blueprints_dir>/<slug>/SPEC.md` — promoted spec snapshot. */
export function blueprintSpecPath(cwd: string, slug: string): string {
  return path.join(blueprintSlugDir(cwd, slug), "SPEC.md");
}

/**
 * `<blueprints_dir>/<slug>/BRIEF.html` — summarized HTML brief
 * (derivative of SPEC.md, generated by `samospec brief`). Lives next
 * to the published spec so static-site hosts (GitHub Pages, GitLab
 * Pages) can serve it under predictable URLs once committed.
 */
export function briefHtmlPath(cwd: string, slug: string): string {
  return path.join(blueprintSlugDir(cwd, slug), "BRIEF.html");
}

/**
 * POSIX-relative spec-slug dir (e.g. `.samo/spec/refunds/`). Used for
 * git operations (`git status --porcelain`, `git show HEAD:<rel>`,
 * `git add` pathspecs) that need a forward-slash, repo-relative path
 * regardless of host platform.
 *
 * Always trailing `/` so consumers can use it as a directory pathspec
 * prefix without re-adding the separator.
 */
export function specSlugDirRelPosix(cwd: string, slug: string): string {
  const rel = resolvePaths(cwd).specDirRel;
  return path.posix.join(rel.split(path.sep).join("/"), slug) + "/";
}

// ---------- internal ----------

function readPathsConfig(cwd: string): PathsConfig {
  const file = path.join(cwd, ".samo", "config.json");
  if (!existsSync(file)) return {};

  let raw: unknown;
  try {
    raw = JSON.parse(readFileSync(file, "utf8"));
  } catch (err) {
    throw new Error(
      `.samo/config.json: not valid JSON: ${(err as Error).message}`,
      { cause: err },
    );
  }
  if (typeof raw !== "object" || raw === null || Array.isArray(raw)) {
    throw new Error(`.samo/config.json: top-level must be a JSON object.`);
  }
  const pathsField = (raw as { paths?: unknown }).paths;
  if (pathsField === undefined) return {};
  if (
    typeof pathsField !== "object" ||
    pathsField === null ||
    Array.isArray(pathsField)
  ) {
    throw new Error(
      `.samo/config.json: \`paths\` must be a JSON object if present.`,
    );
  }
  const parsed = pathsConfigSchema.safeParse(pathsField);
  if (!parsed.success) {
    throw new Error(
      `.samo/config.json: invalid \`paths\` section: ${parsed.error.message}`,
    );
  }
  return parsed.data;
}

function rejectAbsolute(key: string, value: string): void {
  if (path.isAbsolute(value)) {
    throw new Error(
      `.samo/config.json: paths.${key} must be a repo-relative path, got '${value}'.`,
    );
  }
}

/**
 * Refuse path segments that climb out of the repo root via `..`. We
 * resolve against a sentinel root and verify the result stays under
 * it; this catches `../foo`, `foo/../../bar`, and similar.
 */
function rejectEscape(key: string, value: string): void {
  const sentinel = path.resolve("/__samospec_sentinel__");
  const resolved = path.resolve(sentinel, value);
  if (resolved !== sentinel && !resolved.startsWith(`${sentinel}${path.sep}`)) {
    throw new Error(
      `.samo/config.json: paths.${key} must stay inside the repo, got '${value}'.`,
    );
  }
}
